### ISSUE TITLE
flink 能不能支持1.14.4版本

### ISSUE THREAD

**Issue by tpolong** [glink-incubator/glink#2]
![image](https://user-images.githubusercontent.com/13393721/166179177-6a3af7dc-5f6b-4de2-b6f1-24b204769fbe.png)
在windows的ubuntu 22.04lts中运行报错

**Comment by LiebingYu** [comment]
Sorry for the delay. 
I have released a new version 1.0.1 that supports both Flink 1.13 and 1.14. If you want to use a version that supports Flink 1.14, you can download the [source code](https://github.com/glink-incubator/glink/releases/tag/release-1.0.1-1.14) directly and compile it. Or you can use Git directly, as follows.
```
git clone git@github.com:glink-incubator/glink.git
git checkout release-1.0.1-1.14
mvn clean package -DskipTests
```

**Comment by tpolong** [comment]
您好，您的邮件已收到，谢谢！

**Comment by tpolong** [comment]
您好，您的邮件已收到，谢谢！
